### ISSUE TITLE
Typings don't seem to match vis v4.17.0

### ISSUE THREAD

**Issue by damons-sportsbet** [agileek/typings-vis#11]
I've got Vis 4.17.0 and I can't add "color" to an INode with the 1.0.0 typings from this project.

I would expect this to be possible, given the Vis code:

```
function makePageNode(node:SiteNode, parentNode:SiteNode):INode {
	return {
		id: node._id,
		label: node.title,
		shape: "box",
		color: "#112233"
	}
}
```
And the Vis Node javascript class definitely has a color field,
but with these typings I can't use color in the INode. 

It seems like I need to use and INodeOptions object instead but I can't pass a DataSet of those into a Network class. I am happy to fix it if it's an actual problem but I suspect there's something here I don't understand.

**Comment by MichaelBitard** [comment]
I think you are right about that, this is a community driven d.ts so everyone add only what they need.

Feel free to submit a PR, and if you do, it will be nice to change the version of these d.ts in the package.json to reflect the vis.js version.

**Comment by damons-sportsbet** [comment]
Great thanks, I’ve got a few changes already, I’ll raise a PR with the extended INode and bump the version to the vis version.

**Comment by MichaelBitard** [comment]
Closing this, the project has been merged into DefinitelyTyped
