### ISSUE TITLE
Merge the repo into DefinitelyTyped

### ISSUE THREAD

**Issue by maitre-matt** [agileek/typings-vis#13]
The will make the definition easier to consume. PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13092

**Comment by MichaelBitard** [comment]
Thanks, I'm waiting for this to be merged and I will close this repo!

**Comment by maitre-matt** [comment]
I just ported PR https://github.com/agileek/typings-vis/pull/12 to bring the two repoes back in sync.
