### ISSUE TITLE
TimelineOptions on* functions missing implementation (TODO)

### ISSUE THREAD

**Issue by yhamry** [agileek/typings-vis#14]
Hi,

Any news about when onAdd, onDelete, onMove, etc. functions will be available?
I look forward to it.

Thanks,
Omer.

**Comment by MichaelBitard** [comment]
Hi,

This project has been merged into DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/vis

Feel free to submit a PR there.

Regards,
Michaël
