### ISSUE TITLE
Typings only work with a module loader

### ISSUE THREAD

**Issue by clottman** [agileek/typings-vis#6]
It's great to find typings for vis.js, but since the project I'm working on doesn't use a module loader, we're unable to use these. Other libraries like [Underscore.js](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/underscore/underscore.d.ts#L5930) and [Moment.js](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/moment/moment.d.ts#L695) use a static variable declared globally to get around this. (See examples).

**Comment by MichaelBitard** [comment]
I didn't know that, thanks.
I'm away from my computer this week, can you make a Pull Request about that so i'll be able to merge it via smartphone?

**Comment by MichaelBitard** [comment]
Closing this, the project has been merged into DefinitelyTyped
